- name: Ejecutar script sophossetup
  hosts: all  
  become: yes  

  tasks:
  - name: Asignar permisos a sophossetup.sh
    file:
      path: /home/outsupport/sophossetup.sh
      mode: '0700'

  - name: Ejecutar el script para la instalacion de sophos
    script: /home/outsupport/sophossetup.sh
