---
- name: Configuracion de Wazuh para monitoreo de comandos
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.command: echo export PROMPT_COMMAND='RETRN_VAL=$?;logger -t LinuxCommandsWazuh -p local6.debug "User $(whoami) [$$]= $(history 1 | sed "s/^[ ]*[0–9]\+[ ]*//" )"' >> /etc/bash.bashrc
      become: yes

    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.d/bash.conf
        line: local6.* /var/log/commands
        create: yes
        
      
     
