---
- name: Configuracion de Wazuh para monitoreo de comandos
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Agregar linea al final del archivo /etc/bash.bashrc
      ansible.builtin.command: echo export PROMPT_COMMAND='RETRN_VAL=$?;logger -t LinuxCommandsWazuh -p local6.debug "User $(whoami) [$$]: $(history 1 | sed "s/^[ ]*[0–9]\+[ ]*//" )"' >> /etc/bash.bashrc
        
      
     
