---
- name: Configuracion de Wazuh para monitoreo de comandos
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: añadir linea al archivo /etc/bashrc
      ansible.builtin.lineinfile:
        path: /etc/bashrc
        line: export PROMPT_COMMAND='RETRN_VAL=$?;logger -t LinuxCommandsWazuh -p local6.debug "User $(whoami) [$$]= $(history 1 | sed "s/^[ ]*[0–9]\+[ ]*//" )"'
        create: no

    - name: creamos archivo /etc/rsyslog.d/bash.conf y añadimos linea
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.d/bash.conf
        line: local6.* /var/log/commands
        create: yes
        
    - name: Comentamos linea en el archivo /etc/rsyslog.d/50-default.conf
      ansible.builtin.command: sed -i 's/*.*;auth,authpriv.none/#*.*;auth,authpriv.none/g' /etc/rsyslog.d/50-default.conf

    - name: agregamos linea en el archivo /etc/rsyslog.d/50-default.conf
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.d/50-default.conf
        line: "*.*;auth,authpriv.none,local6.none -/var/log/syslog"
        create: no
        
    - name: comentamos lineas en el archivo /etc/rsyslog.conf
      ansible.builtin.shell: |
        sed -i 's/$FileOwner/#$FileOwner/g' /etc/rsyslog.conf
        sed -i 's/$FileGroup/#$FileGroup/g' /etc/rsyslog.conf
        sed -i 's/$FileCreateMode/#$FileCreateMode/g' /etc/rsyslog.conf
        sed -i 's/$DirCreateMode/#$DirCreateMode/g' /etc/rsyslog.conf
        sed -i 's/$Umask/#$Umask/g' /etc/rsyslog.conf
        sed -i 's/$PrivDropToUser/#$PrivDropToUse/g' /etc/rsyslog.conf
        sed -i 's/$PrivDropToGroup/#$PrivDropToGroup/g' /etc/rsyslog.conf
  
    - name: reiniciamos servicio rsyslog
      ansible.builtin.command: systemctl restart rsyslog

    
      
     
